-- =====================================================================
-- Viết feedback buổi học TỪ TRANSCRIPT — đợt 1 (3/12 buổi tháng 9)
-- Ngày chạy: 25/09/2026
-- =====================================================================
--
-- NGUỒN: Google Doc transcript do hệ thống Zoom -> YouTube của cô Ngọc tự
-- sinh. Mỗi doc gồm phần đầu (học viên, ngày, chủ đề, GV, số phút có mặt,
-- link video), phần phân tích tự động (số phút dạy thật, % HV nói, số lượt
-- nói) và transcript đầy đủ có mốc thời gian + nhãn người nói.
--
-- NGUYÊN TẮC ÁP DỤNG KHI VIẾT (theo stop-slop, nhóm A):
--   - Mọi nhận xét phải dẫn được về MỘT mốc thời gian trong video.
--     Không dẫn được thì không viết câu đó.
--   - Không suy ra trình độ CEFR, không bịa nội dung sách.
--   - Chỗ nào là suy đoán thì ghi rõ là suy đoán.
--   - Bài tập về nhà chỉ ghi "đã giao" khi GV thật sự giao trong video.
--     Bài do trung tâm đề xuất phải gắn nhãn [TRUNG TAM DE XUAT].
--
-- ĐÃ LÀM (6 buổi, cả 6 lên QC 100/100 từ 0):
--   1. Vy 24/09       report 2aa244fd  video 0gjG_Ts7rKY
--   2. Công Duy 23/09 report 8d7faa98  video k9F73N0xlpo
--   3. Bé Ngân 23/09  report 1161450d  video ti2sC9-epB8
--   4. Y Khoa 22/09   report be3c3d94  video ifvA9hz4LGw
--   5. Diệp 23/09     report 1827ca67  video cGAAxLfMEt0
--   6. Thảo 23/09     report 6123ff7b  video 2Oj-OQxtSVQ
--
-- CÒN LẠI 6 buổi: Thảo 14/09 · Ngân 16/09 · Ngân 17/09 · Nhi 19/09 ·
--   Duy 21/09 · Thảo 21/09
--
-- =====================================================================
-- PHÁT HIỆN THÊM — đợt 2 (Diệp 23/09 và Thảo 23/09)
-- =====================================================================
--
-- (8) BUỔI DIỆP 23/09 GIẢNG GẦN NHƯ HOÀN TOÀN BẰNG TIẾNG VIỆT.
--     Học viên chỉ đọc từ và câu tiếng Anh, không tự nói câu nào.
--     Diệp học hệ giao tiếp Pre A2. Cần chốt với GV tỉ lệ tiếng Anh
--     tối thiểu trong buổi.
--
-- (9) BUỔI DIỆP 23/09 — NGƯỜI DẠY NÓI TIẾNG VIỆT, CRM GHI Ms. Rose.
--     Đây là gán tạm thời của bản nhập 25/09, đã ghi rõ cần xác nhận.
--     Bằng chứng thêm từ transcript: 48:05 người dạy nói mình dạy học
--     sinh "cấp một tiểu học", 48:13 "dạy thêm ở nhà", 53:05 có con
--     nhỏ 2 tuổi. Sổ Zoom ghi "Rose / Phương" — cần chốt một người.
--
-- (10) BUỔI DIỆP 23/09 — 19 PHÚT THIẾU và 6 PHÚT NGOÀI BÀI.
--      Buổi chạy 56/75 phút. Trong đó 50:58–54:23 GV nói chuyện với
--      con nhỏ của mình trên micro rồi hai cô trò bàn về con GV;
--      44:00–48:46 nói chuyện Trung thu và quà GV mua cho học sinh
--      tiểu học của cô.
--
-- (11) TIÊU ĐỀ SỔ ZOOM GHI SAI "IELTS" cho buổi Thảo 23/09.
--      Buổi đó không có nội dung IELTS nào — thực tế là mẫu câu hỏi
--      sinh hoạt hằng ngày trình độ A1–A2. Nếu xuất báo cáo cho học
--      viên mà để chữ IELTS thì sai. Nên sửa quy tắc đặt tiêu đề.
--
-- (12) LỊCH HỌC CHƯA THỐNG NHẤT GIỮA BA BÊN — buổi Thảo 23/09.
--      40:24–44:34 (4 phút) cô trò dùng giờ lớp để bàn lịch: GV, học
--      viên và cô nước ngoài chưa có lịch chung; học viên phải tự
--      nhắn vào nhóm, GV nói "em hiểu sai tin nhắn của chị". Đây là
--      lỗ hổng vận hành, không phải lỗi của ai. Việc hành chính nên
--      chuyển sang Zalo thay vì dùng giờ lớp có trả tiền.
--
-- (13) KẾ HOẠCH CHUYỂN GIAO CHƯA AI BIẾT — buổi Thảo 23/09.
--      29:44 Ms. Phương nói "vài bữa nữa là chị sẽ học với cô nước
--      ngoài thôi... em thấy chị ổn rồi thì em sẽ thả chị qua đó bơi".
--      Founder nên biết để sắp lịch và tính học phí.
--
-- (14) MỘT HỌC VIÊN CẦN CHĂM SÓC — buổi Thảo 23/09.
--      01:01:14–01:03:17 học viên chia sẻ một biến cố tài chính lớn
--      trong gia đình và đang rất buồn. GV cũng ghi nhận lâu nay đều
--      là học viên chủ động nhắn tin xin học. Đề nghị Founder theo dõi
--      khả năng học viên tạm dừng, và ứng xử tế nhị. Chi tiết không
--      ghi vào hệ thống vì là chuyện riêng — nằm trong video nếu cần.
--
-- =====================================================================
-- BA PHÁT HIỆN PHẢI BÁO FOUNDER — không nằm trong nội dung feedback
-- =====================================================================
--
-- (1) SỬA MỘT CÁO BUỘC SAI VỚI GIÁO VIÊN.
--     Sổ Zoom tự gắn nhãn "Vào dạy muộn" cho buổi Vy 24/09 và Duy 23/09,
--     và bản nhập ngày 25/09 đã chép nguyên nhãn đó vào cột notes.
--     Đọc transcript thì CẢ HAI ĐỀU LÀ HỌC VIÊN VÀO MUỘN:
--       Vy 24/09  [18:58] GV: "why were you late?"
--                 [19:04] HV: "I am in the bathroom to take a shower"
--       Duy 23/09 [12:47] GV: "if you cannot access the link, you can
--                 message me directly" — HV không vào được link.
--     Máy chỉ đo được "19 phút đầu không ai nói" rồi suy ra GV đến muộn.
--     Suy luận đó SAI. Đã sửa lại cột notes của cả hai buổi.
--
-- (2) BUỔI BÉ NGÂN 23/09 CÓ THỂ DO MS. SHEBA DẠY, KHÔNG PHẢI MS. PHƯƠNG.
--     Ảnh hưởng trực tiếp đến lương tháng 9. Bằng chứng:
--       (a) nhãn người nói suốt buổi là "Teacher Sheba";
--       (b) [09:27] GV nói "Philippines is also very hot" — Ms. Sheba ở
--           Philippines, Ms. Phương ở Việt Nam;
--       (c) [42:29] và [50:48] GV nói "I am 26";
--       (d) phòng Zoom dùng PMI 2167216983 — cùng phòng với buổi Vy 24/09
--           của Ms. Sheba;
--       (e) chính sổ Zoom đã ghi "Nhận diện GV: không khớp tên GV".
--     KHÔNG tự đổi giáo viên. Đã ghi cờ vào lessons.notes để Founder quyết.
--
-- (3) BUỔI BÉ NGÂN 23/09 KẾT THÚC SỚM VÌ GIÁO VIÊN ĐAU BỤNG.
--     [54:04] "is it okay if Teacher ends the class early, because
--     teacher's stomach is hurting?" — đây là lý do buổi chỉ 50/60 phút.
--     Sổ Zoom chỉ báo "Dạy thiếu 10 phút" mà không nói vì sao.
--
-- (4) BUỔI Y KHOA 22/09 DO MỘT NGƯỜI KHÔNG CÓ TRONG HỆ THỐNG DẠY.
--     CRM ghi Ms. Phương. [06:18] người dạy tự giới thiệu:
--       "I am a teacher Shane. I am from the Philippines. I am 35 years
--        old. I am a college teacher in the morning, and an ESL teacher
--        in the evening."
--     Ms. Phương là người Việt. Bảng teachers KHÔNG có ai tên Shane —
--     cả đang dạy lẫn đã nghỉ. Đây không phải Ms. Sheba: trong buổi
--     Bé Ngân cùng tuần, Ms. Sheba nói "I am 26".
--     Ảnh hưởng lương tháng 9. Đã gắn cờ, không tự đổi.
--
-- (5) SĨ SỐ LỚP Y KHOA KHÔNG KHỚP.
--     CRM: Ms. Min, Mr. Max, Mr. John.
--     Người dự thật: Mr. Max, Ms. Min, "Ngô Hoàng Tín".
--     Cần xác nhận Ngô Hoàng Tín có phải Mr. John không.
--
-- (6) MỘT LỖI NGỮ PHÁP GIÁO VIÊN DẠY SAI — buổi Y Khoa 22/09.
--     Từ 33:35 đến 35:18, GV lặp 5 lần "Where do you CAME from?" và ở
--     34:44 chốt lại rằng đó là câu đúng. Câu đúng là "Where do you
--     COME from?". Ba học viên là người đi làm, học để giao tiếp công
--     việc — mẫu câu sai được chốt như đúng sẽ thành thói quen khó sửa.
--
-- (7) MỘT DÒNG TỤC TĨU TRONG TRANSCRIPT LÀ LỖI MÁY, KHÔNG PHẢI GV.
--     Dòng 51:55 buổi Y Khoa. Học viên vừa nói "Best? Bist?" khi cố
--     phát âm "beach"; GV nhắc lại "a beach". Máy nhận giọng ghi sai
--     thành một câu chửi. Ghi ra đây để sau này ai đọc transcript
--     không hiểu nhầm.
--
-- =====================================================================
-- Nội dung SQL đã chạy: xem lịch sử thao tác. Ba lệnh chính là
--   update public.teaching_reports set lesson_content/student_quote/
--     strengths/improvements/next_lesson_recommendation/video_timestamp
--     where id in (...)
--   insert into public.homework (...)   -- 3 bài, 1 bài gắn [TRUNG TAM DE XUAT]
--   update public.lessons set notes = ...  -- sửa nhãn sai + gắn cờ GV
-- =====================================================================
